package org.trebor.splink;

import java.util.Random;

public class NameGenerator
{
  private static final Random mRnd = new Random();
  public static final String CAMEL_CASE = "use camel case";
  public static final String INITIAL_CASE_SPACE = "capitalize first letter of very word and seperate with spaces";

  public static void main(String[] args)
  {
    for (int i = 0; i < 10; ++i)
      System.out.println(NameGenerator.getName(2, 3, "-"));
    for (int i = 0; i < 10; ++i)
      System.out.println(NameGenerator.getName(1, 5, INITIAL_CASE_SPACE));
    for (int i = 0; i < 10; ++i)
      System.out.println(NameGenerator.getEmail());
  }
  
  public static String getName(int lowCount, int highCount)
  {
    return getName(lowCount, highCount);
  }
  
  public static String getName(int lowCount, int highCount, String seperator)
  {
    int range = highCount - lowCount;
    int count = mRnd.nextInt(range + 1) + lowCount;
    return getName(count, seperator);
  }
  
  public static String getName(int wordCount)
  {
    return getName(wordCount, "");
  }
  
  public static String getName(int wordCount, String seperator)
  {
    StringBuffer name = new StringBuffer();
    
    for (int i = 0; i < wordCount; ++i)
    {
      String randomName = mNames[mRnd.nextInt(mNames.length)];
      
      if (i > 0 && seperator == CAMEL_CASE)
        randomName = randomName.substring(0,1).toUpperCase() + randomName.substring(1);
      else if (seperator == INITIAL_CASE_SPACE)
        randomName = randomName.substring(0,1).toUpperCase() + randomName.substring(1);

        

      name.append(randomName);
      
      if (i < wordCount - 1 && seperator != CAMEL_CASE && seperator != INITIAL_CASE_SPACE)
        name.append(seperator);
      else if (i < wordCount - 1 && seperator == INITIAL_CASE_SPACE)
        name.append(" ");
    }
      
    return name.toString();
  }
  
  public static String getEmail()
  {
    return String.format("%s@%s.%s", getName(1, 3, CAMEL_CASE), getName(1, "."), getTopLevelDomain());
  }

  public static String getTopLevelDomain()
  {
    return mTldns[mRnd.nextInt(mTldns.length)];
  }
  
  private static final String[] mTldns =
  {
    "com",
    "org",
    "net",
  };
  
  private static final String[] mNames =
  {
    "ball",
    "bat",
    "bed",
    "book",
    "boy",
    "bun",
    "can",
    "cake",
    "cap",
    "car",
    "cat",
    "cow",
    "cub",
    "cup",
    "dad",
    "day",
    "dog",
    "doll",
    "dust",
    "fan",
    "feet",
    "girl",
    "gun",
    "hall",
    "hat",
    "hen",
    "jar",
    "kite",
    "man",
    "map",
    "men",
    "mom",
    "pan",
    "pet",
    "pie",
    "pig",
    "pot",
    "rat",
    "son",
    "sun",
    "toe",
    "tub",
    "van",
    "apple",
    "arm",
    "banana",
    "bike",
    "bird",
    "book",
    "chin",
    "clam",
    "class",
    "clover",
    "club",
    "corn",
    "crayon",
    "crow",
    "crown",
    "crowd",
    "crib",
    "desk",
    "dime",
    "dirt",
    "dress",
    "fang",
    "field",
    "flag",
    "flower",
    "fog",
    "game",
    "heat",
    "hill",
    "home",
    "horn",
    "hose",
    "joke",
    "juice",
    "kite",
    "lake",
    "maid",
    "mask",
    "mice",
    "milk",
    "mint",
    "meal",
    "meat",
    "moon",
    "mother",
    "morning",
    "name",
    "nest",
    "nose",
    "pear",
    "pen",
    "pencil",
    "plant",
    "rain",
    "river",
    "road",
    "rock",
    "room",
    "rose",
    "seed",
    "shape",
    "shoe",
    "shop",
    "show",
    "sink",
    "snail",
    "snake",
    "snow",
    "soda",
    "sofa",
    "star",
    "step",
    "stew",
    "stove",
    "straw",
    "string",
    "summer",
    "swing",
    "table",
    "tank",
    "team",
    "tent",
    "test",
    "toes",
    "tree",
    "vest",
    "water",
    "wing",
    "winter",
    "woman",
    "women",
    "alarm",
    "animal",
    "aunt",
    "bait",
    "balloon",
    "bath",
    "bead",
    "beam",
    "bean",
    "bedroom",
    "boot",
    "bread",
    "brick",
    "brother",
    "camp",
    "chicken",
    "children",
    "crook",
    "deer",
    "dock",
    "doctor",
    "downtown",
    "drum",
    "dust",
    "eye",
    "family",
    "father",
    "fight",
    "flesh",
    "food",
    "frog",
    "goose",
    "grade",
    "grandfather",
    "grandmother",
    "grape",
    "grass",
    "hook",
    "horse",
    "jail",
    "jam",
    "kiss",
    "kitten",
    "light",
    "loaf",
    "lock",
    "lunch",
    "lunchroom",
    "meal",
    "mother",
    "notebook",
    "owl",
    "pail",
    "parent",
    "park",
    "plot",
    "rabbit",
    "rake",
    "robin",
    "sack",
    "sail",
    "scale",
    "sea",
    "sister",
    "soap",
    "song",
    "spark",
    "space",
    "spoon",
    "spot",
    "spy",
    "summer",
    "tiger",
    "toad",
    "town",
    "trail",
    "tramp",
    "tray",
    "trick",
    "trip",
    "uncle",
    "vase",
    "winter",
    "water",
    "week",
    "wheel",
    "wish",
    "wool",
    "yard",
    "zebra",
    "actor",
    "airplane",
    "airport",
    "army",
    "baseball",
    "beef",
    "birthday",
    "boy",
    "brush",
    "bushes",
    "butter",
    "cast",
    "cave",
    "cent",
    "cherries",
    "cherry",
    "cobweb",
    "coil",
    "cracker",
    "dinner",
    "eggnog",
    "elbow",
    "face",
    "fireman",
    "flavor",
    "gate",
    "glove",
    "glue",
    "goldfish",
    "goose",
    "grain",
    "hair",
    "haircut",
    "hobbies",
    "holiday",
    "hot",
    "jellyfish",
    "ladybug",
    "mailbox",
    "number",
    "oatmeal",
    "pail",
    "pancake",
    "pear",
    "pest",
    "popcorn",
    "queen",
    "quicksand",
    "quiet",
    "quilt",
    "rainstorm",
    "scarecrow",
    "scarf",
    "stream",
    "street",
    "sugar",
    "throne",
    "toothpaste",
    "twig",
    "volleyball",
    "wood",
    "wrench",
    "advice",
    "anger",
    "answer",
    "apple",
    "arithmetic",
    "badge",
    "basket",
    "basketball",
    "battle",
    "beast",
    "beetle",
    "beggar",
    "brain",
    "branch",
    "bubble",
    "bucket",
    "cactus",
    "cannon",
    "cattle",
    "celery",
    "cellar",
    "cloth",
    "coach",
    "coast",
    "crate",
    "cream",
    "daughter",
    "donkey",
    "drug",
    "earthquake",
    "feast",
    "fifth",
    "finger",
    "flock",
    "frame",
    "furniture",
    "geese",
    "ghost",
    "giraffe",
    "governor",
    "honey",
    "hope",
    "hydrant",
    "icicle",
    "income",
    "island",
    "jeans",
    "judge",
    "lace",
    "lamp",
    "lettuce",
    "marble",
    "month",
    "north",
    "ocean",
    "patch",
    "plane",
    "playground",
    "poison",
    "riddle",
    "rifle",
    "scale",
    "seashore",
    "sheet",
    "sidewalk",
    "skate",
    "slave",
    "sleet",
    "smoke",
    "stage",
    "station",
    "thrill",
    "throat",
    "throne",
    "title",
    "toothbrush",
    "turkey",
    "underwear",
    "vacation",
    "vegetable",
    "visitor",
    "voyage",
    "year",
    "able",
    "achieve",
    "acoustics",
    "action",
    "activity",
    "aftermath",
    "afternoon",
    "afterthought",
    "apparel",
    "appliance",
    "beginner",
    "believe",
    "bomb",
    "border",
    "boundary",
    "breakfast",
    "cabbage",
    "cable",
    "calculator",
    "calendar",
    "caption",
    "carpenter",
    "cemetery",
    "channel",
    "circle",
    "creator",
    "creature",
    "education",
    "faucet",
    "feather",
    "friction",
    "fruit",
    "fuel",
    "galley",
    "guide",
    "guitar",
    "health",
    "heart",
    "idea",
    "kitten",
    "laborer",
    "language",
    "lawyer",
    "linen",
    "locket",
    "lumber",
    "magic",
    "minister",
    "mitten",
    "money",
    "mountain",
    "music",
    "partner",
    "passenger",
    "pickle",
    "picture",
    "plantation",
    "plastic",
    "pleasure",
    "pocket",
    "police",
    "pollution",
    "railway",
    "recess",
    "reward",
    "route",
    "scene",
    "scent",
    "squirrel",
    "stranger",
    "suit",
    "sweater",
    "temper",
    "territory",
    "texture",
    "thread",
    "treatment",
    "veil",
    "vein",
    "volcano",
    "wealth",
    "weather",
    "wilderness",
    "wren",
    "wrist",
    "writer",
  };
}
